/*
 * generated by Xtext 2.43.0
 */
package one.wilmer.architecture.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ArchSpecUiModule extends AbstractArchSpecUiModule {

	public ArchSpecUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
