/*
 * generated by Xtext 2.43.0
 */
package one.wilmer.architecture.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import one.wilmer.architecture.ArchSpecRuntimeModule;
import one.wilmer.architecture.ArchSpecStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ArchSpecIdeSetup extends ArchSpecStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ArchSpecRuntimeModule(), new ArchSpecIdeModule()));
	}
	
}
