/*
 * generated by Xtext 2.43.0
 */
package one.wilmer.architecture.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ArchSpecProposalProvider extends AbstractArchSpecProposalProvider {
}
