/*
 * generated by Xtext 2.43.0
 */
package one.wilmer.architecture.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class ArchSpecWebModule extends AbstractArchSpecWebModule {
}
