/*
 * generated by Xtext 2.43.0
 */
package one.wilmer.architecture.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import one.wilmer.architecture.ArchSpecRuntimeModule;
import one.wilmer.architecture.ArchSpecStandaloneSetup;
import one.wilmer.architecture.ide.ArchSpecIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class ArchSpecWebSetup extends ArchSpecStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ArchSpecRuntimeModule(), new ArchSpecIdeModule(), new ArchSpecWebModule()));
	}
	
}
