/*
 * generated by Xtext 2.43.0
 */
package one.wilmer.architecture;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArchSpecRuntimeModule extends AbstractArchSpecRuntimeModule {
}
