/*
 * generated by Xtext 2.43.0
 */
package one.wilmer.architecture;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ArchSpecStandaloneSetup extends ArchSpecStandaloneSetupGenerated {

	public static void doSetup() {
		new ArchSpecStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
